#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

%w{ apt elasticsearch java mongodb ntp postfix ubuntu vslinko }.each do |cb|
  cookbook cb
end

cookbook "libvirt", :git => "git://github.com/rithis-chef/cookbook-libvirt"
cookbook "ignis", :git => "git://github.com/vivus-ignis/cookbook-ignis"
cookbook "ark", :git => "git://github.com/RallySoftware-cookbooks/ark",
  :ref => "COOK-3065"

%w{ application cache database host promo tarsnap }.each do |suffix|
  cookbook "skveez_#{suffix}", :path => "my_cookbooks/skveez_#{suffix}"
end
