#!/usr/bin/env ruby
#^syntax detection

site "http://community.opscode.com/api/v1"

%w{ apt elasticsearch java mongodb ntp ubuntu vslinko }.each do |cb|
  cookbook cb
end

cookbook "libvirt", :github => "rithis/cookbook-libvirt"

%w{ application database host }.each do |suffix|
  cookbook "skveez_#{suffix}", :path => "skveez/#{suffix}"
end
