#!/bin/sh

. /usr/local/etc/mysql_backup.conf

if mkdir $LOCKDIR 2>/dev/null; then
    OUTPUT_LOG=`mktemp /tmp/mysql_backup_full.XXXXXX`
    trap "rm -f $OUTPUT_LOG; rm -rf $LOCKDIR" 0 2 3 15 
else
    echo "Lockdir already exists" | mail -s "MySQL full backup failed @ `hostname`" $MAILTO_REPORTS
    exit 1
fi
rm -rf $BACKUP_DIR_FULL/*
rm -rf $BACKUP_DIR_INCR/*
innobackupex --user=$BACKUP_USER \
             --password=$BACKUP_PASSWORD \
             $BACKUP_DIR_FULL > $OUTPUT_LOG 2>&1
grep -q "innobackupex: completed OK!" $OUTPUT_LOG
if [ $? != 0 ]; then
    cat $OUTPUT_LOG | mail -s "MySQL full backup failed @ `hostname`" $MAILTO_REPORTS
fi

